
/* Table: book_reviews */
DROP TABLE IF EXISTS `book_reviews`;
CREATE TABLE `book_reviews` (
  `id` int NOT NULL AUTO_INCREMENT,
  `book_id` int DEFAULT NULL,
  `user_name` varchar(255) DEFAULT NULL,
  `rating` int DEFAULT NULL,
  `review` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `book_id` (`book_id`),
  CONSTRAINT `book_reviews_ibfk_1` FOREIGN KEY (`book_id`) REFERENCES `books` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
INSERT INTO `book_reviews` VALUES
(4, 5, 'Pushkraj Kulkarni ', 5, 'Very Emotional', '2026-02-14 18:51:40.000');


/* Table: books */
DROP TABLE IF EXISTS `books`;
CREATE TABLE `books` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `poster` text,
  `description` text,
  `author` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
INSERT INTO `books` VALUES
(1, 'Words of Radiance', 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e0/WordsOfRadianceCover.png/250px-WordsOfRadianceCover.png', 'An epic fantasy novel continuing the Stormlight Archive series, following Kaladin, Shallan, and Dalinar as they face political turmoil and ancient threats.', 'Brandon Sanderson'),
(2, 'Harry Potter and The Deathly Hollows', 'Final installment of the Harry Potter series where Harry faces Voldemort in the ultimate battle between good and evil.', 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a9/Harry_Potter_and_the_Deathly_Hallows.jpg/250px-Harry_Potter_and_the_Deathly_Hallows.jpg', 'J.K. Rowling'),
(3, 'Fourth King', 'https://upload.wikimedia.org/wikipedia/en/thumb/d/dd/Fourth_Wing_Cover_Art.jpeg/250px-Fourth_Wing_Cover_Art.jpeg', 'Historical fiction novel exploring themes of leadership, faith, and power set against a dramatic political backdrop.', 'K.M. Munshi'),
(4, 'Mrutyanjay', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Mrityunjay-tv_serial.png/250px-Mrityunjay-tv_serial.png', 'Mythological novel narrating the life of Karna from the Mahabharata, focusing on his struggles, loyalty, and tragic destiny.', 'Shivaji Sawant'),
(5, 'Shyam Chi Aai', 'https://cdn.exoticindia.com/images/products/original/books-2019/qzz217b.jpg', 'Emotional autobiographical novel portraying the deep bond between a mother and son and the values she instills.', 'Sane Guruji'),
(6, 'Batatyachi Chaal', 'https://rekhtabooks.com/cdn/shop/files/Batatychi-Chawl.jpg?v=1727351766', 'Humorous Marathi novel depicting middle-class life in Mumbai through witty characters and social satire.', 'P.L. Deshpande'),
(7, 'Godan', 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b7/Godaan_by_Munshi_Premchand.png/250px-Godaan_by_Munshi_Premchand.png', 'Classic Hindi novel portraying rural India, poverty, and the struggles of a farmer named Hori.', 'Munshi Premchand'),
(8, 'Nirmala', 'https://upload.wikimedia.org/wikipedia/en/7/70/Nirmala_novel_cover.jpg', 'Social reform novel addressing child marriage and the hardships faced by women in traditional Indian society.', 'Munshi Premchand'),
(9, 'Raag Darbari', 'https://www.surjeetpublications.com/image/cache/data/surjeet/product/update-june2018/Raag-Darbari-228x334.jpg', 'Satirical Hindi novel exposing political corruption and social issues in post-independence rural India.', 'Shri Lal Shukla'),
(10, 'Know My Name', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1567612158l/50196744.jpg', 'Memoir recounting the author?s experience with sexual assault and the legal system, highlighting resilience and justice.', 'Chanel Miller'),
(11, 'Crooked Kingdom', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1456172607i/22299763.jpg', 'Fantasy sequel to Six of Crows where Kaz Brekker and his crew plan a daring revenge in a dangerous underworld.', 'Leigh Bardugo'),
(12, 'A Court of Mist and Fury', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1620325671i/50659468.jpg', 'Fantasy romance novel following Feyre as she navigates political alliances and personal transformation in Prythian.', 'Sarah J. Maas'),
(13, 'The Return of the King', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1654216226i/61215384.jpg', 'Final part of The Lord of the Rings trilogy detailing the climactic battle for Middle-earth and Frodo?s quest.', 'J.R.R. Tolkien'),
(14, 'The House of Hades', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1464201430i/12127810.jpg', 'Fantasy adventure from the Heroes of Olympus series where Percy and Annabeth face dangers in the Underworld.', 'Rick Riordan'),
(15, 'kingdom of Ash', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1673567331i/76715522.jpg', 'Epic conclusion to the Throne of Glass series, focusing on war, sacrifice, and destiny.', 'Sarah J. Maas'),
(16, 'The Nightingale', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1681839850i/21853621.jpg', 'Historical fiction set during World War II, telling the story of two sisters in Nazi-occupied France.', 'Kristin Hannah'),
(17, 'Light Bringer', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1667655583i/29227774.jpg', 'Epic fantasy novel exploring power struggles, war, and destiny in a richly built fictional world.', 'Pierce Brown'),
(18, 'The Complete Maus', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1327354180i/15195.jpg', 'Graphic novel depicting the Holocaust through anthropomorphic characters, blending history and memoir.', 'Art Spiegelman'),
(19, 'Heartstopper: Volume Four', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1640745736i/56060300.jpg', 'Young adult graphic novel focusing on friendship, love, and self-discovery among teenagers.', 'Alice Oseman'),
(20, 'Just Mercy', 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1635827409i/20342617.jpg', 'Nonfiction work highlighting injustice in the American legal system and the fight for equal justice.', 'Bryan Stevenson'),
(21, 'Yayati', 'https://upload.wikimedia.org/wikipedia/en/thumb/5/52/Yayati_English_translation_cover.jpeg/250px-Yayati_English_translation_cover.jpeg', 'Mythological Marathi novel retelling the story of King Yayati and his moral dilemmas.', 'V.S. Khandekar'),
(22, 'Kosala', 'https://upload.wikimedia.org/wikipedia/en/thumb/5/54/Cocoon_Bhalchandra_Nemade.jpeg/250px-Cocoon_Bhalchandra_Nemade.jpeg', 'Modern Marathi novel portraying the inner turmoil and experiences of a young man navigating life.', 'Bhalchandra Nemade'),
(23, 'Rau', 'https://upload.wikimedia.org/wikipedia/en/3/35/Front_cover_-_Rau_%28marathi_novel%29_1972.jpg', 'Historical novel based on the life of Peshwa Bajirao I and his love story with Mastani.', 'N.S. Inamdar'),
(24, 'Pan Lakshyat Kon Gheto', 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6a/Pan_Lakshat_Kon_Gheto_cover.jpg/250px-Pan_Lakshat_Kon_Gheto_cover.jpg', 'Classic Marathi novel addressing social reform and the plight of women in traditional society.', 'H.N. Apte'),
(25, 'Mahanayak', 'https://upload.wikimedia.org/wikipedia/en/9/92/Mahanayak_%28novel%29.jpg', 'Biographical novel based on the life of Subhas Chandra Bose and India?s freedom struggle.', 'Vishwas Patil'),
(26, 'Duniyadari', 'https://m.media-amazon.com/images/I/31UuT0c8dyL._FMwebp_.jpg', 'Popular Marathi novel about college life, friendships, love, and emotional growth.', 'Suhas Shirvalkar'),
(27, 'Ek Hota Carver', 'https://m.media-amazon.com/images/I/41x2pSSCV1L._SX342_SY445_FMwebp_.jpg', 'Marathi biographical novel inspired by the life of scientist George Washington Carver.', 'Veena Gavankar'),
(28, 'Rita Welinkar', 'https://www.gutenberg.org/cache/epub/24827/pg24827.cover.medium.jpg', 'Psychological Marathi novel exploring identity, relationships, and emotional conflict.', 'Shanta Gokhale'),
(29, 'Bangarwadi', 'https://m.media-amazon.com/images/I/412XP5YMjqL._SX342_SY445_FMwebp_.jpg', 'Marathi novel portraying rural life and the challenges of a village schoolteacher.', 'Vyankatesh Madgulkar'),
(30, 'Asa Mi Asami', 'https://m.media-amazon.com/images/I/31GToS4D9+L.jpg', 'Humorous Marathi novel highlighting the everyday struggles of a middle-class man.', 'P.L. Deshpande'),
(31, 'Gaban', 'https://upload.wikimedia.org/wikipedia/en/c/c5/Gaban_%28novel%29.jpg', 'Novel exploring moral dilemmas, greed, and social pressures in Indian society.', 'Munshi Premchand'),
(32, 'Rashmirathi', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJCXdhLVZ08fzhwITg27MiwgRn4WtF54ca8Q&s', 'Epic Hindi poem centered on Karna from the Mahabharata, celebrating valor and tragedy.', 'Ramdhari Singh Dinkar'),
(33, 'Madhushala', 'https://upload.wikimedia.org/wikipedia/en/thumb/8/82/Madhushala.jpg/250px-Madhushala.jpg', 'Famous Hindi poetic work using the metaphor of a tavern to explore life and philosophy.', 'Harivansh Rai Bachchan'),
(34, 'Gunaho Ka Devta', 'https://m.media-amazon.com/images/I/41zAs+uVE6L._SY445_SX342_FMwebp_.jpg', 'Romantic Hindi novel depicting intense emotions and unfulfilled love.', 'Dharamvir Bharati'),
(35, 'Maila Anchal', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Maila_anchal_Front.jpg/250px-Maila_anchal_Front.jpg', 'Regional Hindi novel portraying rural Bihar and its socio-political realities.', 'Phanishwar Nath Renu'),
(36, 'Kamayani', 'https://m.media-amazon.com/images/I/81cXchJoVFL._SY466_.jpg', 'Philosophical epic poem blending mythology and human psychology.', 'Jaishankar Prasad'),
(37, 'Tamas', 'https://m.media-amazon.com/images/I/81faMT-cnzL._SY466_.jpg', 'Novel set during the partition of India, depicting communal tensions and human suffering.', 'Bhisham Sahni'),
(38, 'Chandrakanta', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3XDMsqJOBaOuNkZbJGUL-rR0oxAqvQiDxDQ&s', 'Fantasy romance novel filled with adventure, magic, and royal intrigue.', 'Devaki Nandan Khatri'),
(39, 'Parineeta', 'https://m.media-amazon.com/images/I/61gcYLDVXcL._SY466_.jpg', 'Classic romantic novel exploring love, class differences, and societal expectations.', 'Sarat Chandra Chattopadhyay'),
(40, 'Zindanginama', 'https://cdn.kobo.com/book-images/0ce396b1-335a-4313-aa36-5f6f534c7143/1200/1200/False/zindaginama.jpg', 'Historical Hindi novel portraying rural Punjabi life before independence.', 'Krishna Sobti');


/* Table: movies */
DROP TABLE IF EXISTS `movies`;
CREATE TABLE `movies` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `description` text,
  `cast_members` text,
  `poster` varchar(500) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `cast` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=52 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
INSERT INTO `movies` VALUES
(1, 'The Godfather', 'The Godfather is a legendary crime drama that explores the world of an Italian-American mafia family. The story revolves around Vito Corleone, the powerful and respected head of the Corleone crime family in New York. When an attempt is made on his life, the responsibility of protecting the family gradually falls on his youngest son, Michael Corleone, who initially wants nothing to do with the family business. As Michael is drawn deeper into the violent underworld, he transforms from a quiet war hero into a ruthless and calculating mafia boss. The film highlights themes of power, loyalty, family, betrayal, and morality.', 'Marlon Brando, Al Pacino, James Caan, Robert Duvall, Diane Keaton, John Cazale', 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', '2026-02-09 20:17:23.000', NULL),
(2, '3 Idiots', '3 Idiots is a coming-of-age comedy-drama that follows the journey of three engineering students?Rancho, Farhan, and Raju?at an elite Indian college. Through humor, friendship, and emotional moments, the film questions the pressure-driven education system and encourages students to follow their passion rather than societal expectations. The story alternates between their college days and a present-day search for their long-lost friend Rancho.', 'Aamir Khan, R. Madhavan, Sharman Joshi, Kareena Kapoor Khan, Boman Irani', 'https://wallpapercave.com/wp/wp6568157.jpg', '2026-02-09 21:28:22.000', NULL),
(3, 'Duniyadari', 'Duniyadari is a Marathi romantic drama that explores friendship, love, betrayal, and ambition. The story follows a law student whose life takes a drastic turn due to misunderstandings, broken relationships, and the harsh realities of the outside world. The film highlights emotional conflicts, loyalty among friends, and the consequences of choices made in youth.', 'Swapnil Joshi, Sai Tamhankar, Jitendra Joshi, Urmila Kanitkar, Ashok Saraf', 'https://wallpapercave.com/wp/wp8340497.jpg', '2026-02-09 21:41:05.000', NULL),
(4, 'The Shawshank Redemption', 'The Shawshank Redemption is a powerful prison drama that follows the life of Andy Dufresne, a banker wrongly convicted of murdering his wife and her lover. Inside Shawshank State Penitentiary, Andy forms an unlikely friendship with fellow inmate Ellis ?Red? Redding. Through patience, intelligence, and quiet resilience, Andy maintains hope and dignity in a harsh environment, ultimately redefining the meaning of freedom and redemption.', 'Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler, Clancy Brown', 'https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg', '2026-02-09 21:46:19.000', NULL),
(5, 'Gangs of Wasseypur', 'Gangs of Wasseypur is an epic crime drama that chronicles the violent power struggles between rival coal mafia families in the town of Wasseypur over several decades. The film follows the rise of Sardar Khan and his sons as they seek revenge, control, and dominance, exploring themes of betrayal, ambition, and the cyclical nature of violence.', 'Manoj Bajpayee, Nawazuddin Siddiqui, Richa Chadha, Pankaj Tripathi, Tigmanshu Dhulia, Jaideep Ahlawat', 'https://wallpapercave.com/wp/wp6653101.jpg', '2026-02-09 21:50:22.000', NULL),
(6, 'Sairat', 'Sairat is a Marathi romantic drama that portrays the intense love story of Archi and Parshya, two young individuals from different social and caste backgrounds. Set against a rural backdrop, the film explores themes of love, honor, societal pressure, and the harsh consequences faced by those who challenge deep-rooted traditions. The movie is known for its raw emotions and realistic storytelling.', 'Rinku Rajguru, Akash Thosar, Tanaji Galgunde, Bhushan Patil', 'https://thereviewmonk.com/assets/media/movies/posters/w300/7c7c4e6f534f3595025d70e6725000ac.jpg', '2026-02-10 20:22:08.000', NULL),
(7, 'Natsamrat', 'Natsamrat is a powerful Marathi drama that follows the life of Ganpat Ramchandra Belwalkar, a celebrated stage actor who retires after giving his entire life to theatre. Expecting love and respect from his children, he instead faces neglect and humiliation. The film explores themes of aging, dignity, family responsibility, and the emotional struggles of an artist in his final years.', 'Nana Patekar, Medha Manjrekar, Mrinal Kulkarni, Vikram Gokhale', 'https://wallpapercave.com/wp/wp10642383.jpg', '2026-02-10 20:23:15.000', NULL),
(8, 'Fight Club', 'Fight Club is a psychological thriller that follows an unnamed office worker suffering from insomnia and dissatisfaction with modern consumer culture. He forms an underground fight club with the mysterious Tyler Durden, which soon evolves into something far more dangerous. The film explores themes of identity, rebellion, masculinity, and the consequences of uncontrolled chaos.', 'Brad Pitt, Edward Norton, Helena Bonham Carter, Meat Loaf', 'https://wallpapercave.com/wp/wp12086598.jpg', '2026-02-10 20:24:09.000', NULL),
(9, 'Dangal', 'Dangal is a biographical sports drama based on the life of former wrestler Mahavir Singh Phogat, who trains his daughters Geeta and Babita to become world-class wrestlers. The film highlights gender equality, determination, discipline, and the struggles faced in breaking social stereotypes in India.', 'Aamir Khan, Fatima Sana Shaikh, Sanya Malhotra, Sakshi Tanwar', 'https://wallpapercave.com/wp/wp4627605.jpg', '2026-02-10 20:25:21.000', NULL),
(10, 'Dashavatar', 'Dashavatar is an animated mythological film based on the ten incarnations of Lord Vishnu. The movie blends Indian mythology with animation, narrating stories of good versus evil through avatars like Matsya, Kurma, Varaha, Narasimha, Rama, Krishna, and Kalki, emphasizing dharma and balance in the universe.', 'Dilip Prabhawalkar, Mahesh Manjrekar, Siddharth Menon, Priyadarshini Indalkar', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT53oVqNeFPUzl35_sDApF8xoZ0ElHETSvsnw&s', '2026-02-10 20:39:00.000', NULL),
(11, 'Dhurandhar', 'Dhurandhar is an upcoming Hindi action-drama film starring Ranveer Singh in a powerful and intense role. The movie revolves around a fearless and ruthless protagonist who rises against corruption and injustice in a violent and politically charged environment. Known for its raw storytelling, high-octane action, and mass appeal, Dhurandhar showcases Ranveer Singh in a larger-than-life avatar.', 'Ranveer Singh, Akshaye Khanna, Sanjay Dutt, Arjun Rampal, Madhavan', 'https://wallpapercave.com/wp/wp15992879.jpg', '2026-02-10 21:06:55.000', NULL),
(12, 'Oppenheimer', 'Oppenheimer is a biographical historical drama directed by Christopher Nolan. The film follows the life of J. Robert Oppenheimer, the brilliant physicist who played a key role in the development of the atomic bomb during World War II as part of the Manhattan Project. As scientific ambition collides with moral responsibility, the movie explores themes of power, guilt, politics, and the devastating consequences of human innovation.', 'Cillian Murphy, Robert Downey Jr., Emily Blunt, Matt Damon, Florence Pugh', 'https://image.tmdb.org/t/p/w500/ptpr0kGAckfQkJeJIt8st5dglvd.jpg', '2026-02-10 21:07:46.000', NULL),
(13, 'Dev Manus', 'Dev Manus is a Marathi crime drama film inspired by real-life events. The story follows a seemingly kind and helpful man who hides a dark and disturbing secret behind his benevolent nature. As the narrative unfolds, the film explores psychological manipulation, trust, and the frightening reality of how evil can exist behind an innocent face.', 'Mahesh Manjrekar, Siddharth Bodke, Renuka Shahane, Subodh Bhave, Abhijeet Khandkekar', 'https://resizing.flixster.com/7Khg08DHMRQ6HvF0VypOcCYpWH8=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2RhNmIxMzE2LWU4YmMtNGQ5Zi05NmNiLWJmMzEyY2Q4MTA3Yy5qcGc=', '2026-02-10 21:14:36.000', NULL),
(14, 'Chhaava', 'Chhaava is a historical action drama based on the life of Chhatrapati Sambhaji Maharaj, the brave son of Chhatrapati Shivaji Maharaj. The film portrays his unmatched courage, sacrifice, and resistance against the Mughal Empire. It highlights themes of valor, loyalty, and patriotism while showcasing the harsh realities of war and leadership.', 'Vicky Kaushal, Rashmika Mandanna, Akshaye Khanna', 'https://wallpapercave.com/wp/wp15066594.webp', '2026-02-10 21:16:04.000', NULL),
(15, 'John Wick : Chapter 4', 'John Wick: Chapter 4 is an action thriller that follows legendary assassin John Wick as he uncovers a path to finally defeat the High Table. Hunted across the globe, John faces powerful new enemies and old rivals, leading to relentless action, intense combat sequences, and a final confrontation that tests his endurance, loyalty, and will to survive.', 'Keanu Reeves, Donnie Yen, Bill Skarsgård, Laurence Fishburne, Ian McShane', 'https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg', '2026-02-10 21:17:52.000', NULL),
(16, 'Jarann', 'Jarann is a Marathi psychological thriller that delves into superstition, blind faith, and the dark consequences of social manipulation. Set in a rural backdrop, the film explores how fear and belief systems can be weaponized, slowly unraveling the lives of ordinary people as tension and mystery build toward a disturbing truth.', 'Amruta Subhash, Kishor Kadam, Anita Date', 'https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/jarann-et00446492-1747488540.jpg', '2026-02-10 21:19:05.000', NULL),
(17, 'War 2', 'War 2 is an upcoming high-octane Hindi action thriller and a sequel to the blockbuster film War (2019). The movie continues the story within the YRF Spy Universe, featuring intense espionage, large-scale action sequences, and global missions. With powerful rivals facing off, War 2 promises adrenaline-pumping stunts, sharp twists, and a clash of elite agents driven by duty, patriotism, and personal conflict.', 'Hrithik Roshan, N. T. Rama Rao Jr., Kiara Advani', 'https://upload.wikimedia.org/wikipedia/hi/f/f5/War_2_official_poster.jpg?20250520063337', '2026-02-10 21:20:42.000', NULL),
(18, 'Mission: Impossible ? Dead Reckoning Part One', 'Mission: Impossible ? Dead Reckoning Part One is a high-stakes action espionage thriller that follows Ethan Hunt and the IMF team as they race against time to stop a powerful and dangerous artificial intelligence that threatens global security. With missions spanning multiple countries, the film delivers breathtaking stunts, intense chases, and complex moral choices as Ethan confronts enemies from his past and an uncertain future.', 'Tom Cruise, Hayley Atwell, Ving Rhames, Simon Pegg, Rebecca Ferguson', 'https://image.tmdb.org/t/p/w500/NNxYkU70HPurnNCSiCjYAmacwm.jpg', '2026-02-10 21:21:54.000', NULL),
(19, 'Mulshi Pattern', 'Mulshi Pattern is a Marathi crime drama that portrays the dark consequences of land acquisition and rapid urbanization. The story follows Rahul Patil, a farmer?s son who turns into a gangster after losing his ancestral land, highlighting the socio-economic conflict between villagers and developers.', 'Om Bhutkar, Mohan Joshi, Upendra Limaye, Kshitij Date', 'https://wallpapercave.com/wp/wp7050029.jpg', '2026-02-10 20:27:33.000', NULL),
(20, 'Gulkand', 'Gulkand is a Marathi romantic drama that explores modern relationships, love, and emotional compatibility in today?s generation. The film focuses on two individuals navigating misunderstandings, personal growth, and the complexities of commitment. With a light-hearted yet meaningful narrative, Gulkand highlights how communication and trust shape relationships in contemporary society.', 'Sai Tamhankar, Prasad Oak', 'https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Gulkand_film.jpg/250px-Gulkand_film.jpg', '2026-02-10 21:26:06.000', NULL),
(21, 'The Dark Knight', 'The Dark Knight follows Batman as he faces his most dangerous enemy, the Joker, a criminal mastermind who seeks to plunge Gotham City into chaos. As Batman struggles with moral dilemmas and escalating violence, he must choose between being a hero and becoming what the city needs to survive.', 'Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine, Gary Oldman, Maggie Gyllenhaal', 'https://upload.wikimedia.org/wikipedia/en/thumb/1/1c/The_Dark_Knight_%282008_film%29.jpg/250px-The_Dark_Knight_%282008_film%29.jpg', '2026-02-10 22:10:47.000', NULL),
(22, 'Interstellar', 'Interstellar is a science fiction epic that explores humanity?s quest for survival beyond Earth. Set in a future where Earth is becoming uninhabitable, a group of astronauts travel through a wormhole in search of a new home for mankind. The film combines emotional storytelling with complex scientific concepts such as time dilation, space travel, and black holes.', 'Matthew McConaughey, Anne Hathaway, Jessica Chastain, Michael Caine', 'https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg', '2026-02-10 22:38:04.000', NULL),
(23, 'Inception', 'Inception is a science fiction thriller directed by Christopher Nolan. The film follows a skilled thief who specializes in stealing secrets from within the subconscious during the dream state. He is given a chance at redemption by performing the impossible task of planting an idea into someone?s mind, leading to a complex and visually stunning exploration of reality, dreams, and time.', 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page, Tom Hardy, Ken Watanabe', 'https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg', '2026-02-10 22:40:26.000', NULL),
(24, 'Scarface', 'Scarface is a crime drama film that follows the rise and fall of Tony Montana, a Cuban immigrant who becomes a powerful drug lord in Miami. Driven by ambition, greed, and a hunger for power, Tony builds a criminal empire but slowly descends into paranoia and violence. The film explores themes of the American Dream, excess, loyalty, and the consequences of unchecked ambition.', 'Al Pacino, Michelle Pfeiffer, Steven Bauer, Mary Elizabeth Mastrantonio', 'https://upload.wikimedia.org/wikipedia/en/thumb/7/71/Scarface_-_1983_film.jpg/250px-Scarface_-_1983_film.jpg', '2026-02-10 22:42:11.000', NULL),
(25, 'Avengers: Endgame', 'Avengers: Endgame is a superhero epic that concludes the Infinity Saga of the Marvel Cinematic Universe. After the devastating events caused by Thanos, the remaining Avengers unite to undo the damage and restore balance to the universe. The film explores themes of sacrifice, loss, teamwork, and hope while delivering large-scale action and emotional character arcs.', 'Robert Downey Jr., Chris Evans, Chris Hemsworth, Mark Ruffalo, Scarlett Johansson, Jeremy Renner, Josh Brolin', 'https://upload.wikimedia.org/wikipedia/en/0/0d/Avengers_Endgame_poster.jpg', '2026-02-10 22:51:59.000', NULL),
(26, 'Fast & Furious 7', 'Fast & Furious 7 continues the high-octane saga of Dominic Toretto and his crew as they face a new and highly skilled adversary, Deckard Shaw, who seeks revenge for his brother?s defeat. The film moves across global locations?Los Angeles, Abu Dhabi, and Azerbaijan?blending intense street racing, espionage-style action, and large-scale stunts. It also serves as an emotional tribute to Paul Walker, concluding his character Brian O?Conner?s journey in the franchise.', 'Vin Diesel, Paul Walker, Jason Statham, Dwayne Johnson, Ludacris', 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b8/Furious_7_poster.jpg/250px-Furious_7_poster.jpg', '2026-02-11 14:32:00.000', NULL),
(27, 'Men In Black 3', 'Men in Black 3 is a science fiction action-comedy film directed by Barry Sonnenfeld. When a dangerous alien criminal named Boris the Animal escapes from a high-security lunar prison, he alters history by traveling back to 1969 to kill Agent K and change the future. To restore the timeline and save his partner, Agent J travels back in time to work with a younger version of Agent K. The film blends time-travel mechanics, alien threats, humor, and emotional depth, while expanding the mythology of the Men in Black organization.', 'Will Smith, Tommy Lee Jones, Josh Brolin, Jemaine Clement, Emma Thompson', 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8a/Men_In_Black_3.jpg/250px-Men_In_Black_3.jpg', '2026-02-11 14:35:05.000', NULL),
(28, 'Cars 2', 'Cars 2 is an animated action-comedy film produced by Pixar Animation Studios. The story follows Lightning McQueen as he competes in the World Grand Prix, an international racing competition designed to promote alternative fuel. Meanwhile, his best friend Mater accidentally gets involved in a global espionage mission after being mistaken for a secret agent. As racing and spy action collide across Japan, Italy, and the United Kingdom, the film combines humor, high-speed adventure, and themes of friendship and loyalty.', 'Owen Wilson, Larry the Cable Guy, Michael Caine, Emily Mortimer, John Turturro, Eddie Izzard', 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7f/Cars_2_Poster.jpg/250px-Cars_2_Poster.jpg', '2026-02-11 14:43:08.000', NULL),
(29, 'BABY DRIVER', 'Baby Driver is a 2017 action crime film directed by Edgar Wright. The story follows Baby, a talented young getaway driver who relies on music to drown out his tinnitus and enhance his precision driving skills. Forced to work for a crime boss named Doc, Baby becomes entangled in a dangerous heist crew. As he falls in love with Debora and dreams of leaving his criminal life behind, one final job threatens his chance at freedom, leading to intense car chases and high-stakes confrontations.', 'Ansel Elgort, Kevin Spacey, Lily James, Jon Hamm, Jamie Foxx, Eiza Gonzalez, Jon Bernthal', 'https://upload.wikimedia.org/wikipedia/en/8/8e/Baby_Driver_poster.jpg', '2026-02-11 14:44:47.000', NULL),
(30, 'Ford v Ferrari', 'Ford v Ferrari is a 2019 biographical sports drama film directed by James Mangold. The film tells the true story of visionary car designer Carroll Shelby and fearless British driver Ken Miles, who are tasked by Ford Motor Company to build a revolutionary race car capable of defeating Ferrari at the 24 Hours of Le Mans in 1966. Facing corporate resistance, technical challenges, and intense rivalry, the team pushes the limits of engineering and endurance in one of the most legendary battles in motorsport history.', 'Matt Damon, Christian Bale, Jon Bernthal, Caitriona Balfe, Tracy Letts, Josh Lucas', 'https://upload.wikimedia.org/wikipedia/en/a/a4/Ford_v._Ferrari_%282019_film_poster%29.png', '2026-02-11 14:49:15.000', NULL),
(31, 'Sigham', 'Singham is a 2011 Hindi action film directed by Rohit Shetty. The story follows Bajirao Singham, an honest and fearless police officer posted in a small Goan village. His life changes when he clashes with Jaikant Shikre, a powerful and corrupt politician who abuses his influence to control the system. Transferred to Mumbai as punishment, Singham takes a firm stand against corruption and fights to restore justice, using both integrity and strength to protect the common people.', 'Ajay Devgn, Kajal Aggarwal, Prakash Raj, Ashok Saraf, Sachin Khedekar', 'https://upload.wikimedia.org/wikipedia/en/thumb/a/ac/Singham_%282011_Hindi_film%29_Theatrical_poster.jpg/250px-Singham_%282011_Hindi_film%29_Theatrical_poster.jpg', '2026-02-11 15:04:47.000', NULL),
(32, 'The Kashmir Files', 'The Kashmir Files is a 2022 Hindi drama film directed by Vivek Ranjan Agnihotri. The film portrays the exodus of Kashmiri Pandits from the Kashmir Valley in the early 1990s through the perspective of a young student who uncovers the truth about his family?s past. It explores themes of displacement, trauma, political conflict, and the search for justice, presenting a narrative centered on historical events and personal loss.', 'Anupam Kher, Mithun Chakraborty, Darshan Kumar, Pallavi Joshi, Chinmay Mandlekar', 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d4/The_Kashmir_Files_poster.jpg/250px-The_Kashmir_Files_poster.jpg', '2026-02-11 15:08:26.000', NULL),
(33, 'Golmaal 3', 'Golmaal 3 is a 2010 Hindi comedy film directed by Rohit Shetty. The story revolves around two rival groups of siblings who are constantly at odds due to their parents? past misunderstandings. When their single parents reunite and decide to marry, the children must put aside their differences. Packed with slapstick humor, exaggerated action sequences, and comic misunderstandings, the film blends family drama with high-energy entertainment.', 'Ajay Devgn, Kareena Kapoor, Arshad Warsi, Tusshar Kapoor, Shreyas Talpade, Kunal Khemu, Mithun Chakraborty', 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f4/Golmaal_3.jpg/250px-Golmaal_3.jpg', '2026-02-11 15:12:23.000', NULL),
(34, 'Phir Hera Pheri', 'Phir Hera Pheri is a 2006 Hindi comedy film directed by Neeraj Vora. A sequel to Hera Pheri, the film follows Raju, Shyam, and Baburao as they become wealthy after their previous adventure but soon lose everything in a fraudulent investment scheme. Desperate to recover their money, the trio gets entangled with gangsters, con artists, and hilarious misunderstandings, leading to chaotic and comic situations.', 'Akshay Kumar, Suniel Shetty, Paresh Rawal, Bipasha Basu, Rimi Sen, Rajpal Yadav', 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3a/Still-phir-hera-phir.jpg/250px-Still-phir-hera-phir.jpg', '2026-02-12 11:40:59.000', NULL),
(35, 'De Dana Dan', 'De Dana Dan is a 2009 Hindi comedy film directed by Priyadarshan. The story revolves around two struggling friends who attempt to kidnap their girlfriends? wealthy dog to extort ransom money and solve their financial problems. Their plan spirals out of control, leading to chaos inside a luxury hotel filled with gangsters, mistaken identities, and nonstop comic confusion.', 'Akshay Kumar, Suniel Shetty, Katrina Kaif, Paresh Rawal, Sameera Reddy, Neha Dhupia', 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2b/Dedanadan.jpg/250px-Dedanadan.jpg', '2026-02-12 11:45:04.000', NULL),
(36, 'Dhamaal', 'Dhamaal is a 2007 Hindi adventure comedy film directed by Indra Kumar. The story follows four unemployed friends who learn about a hidden treasure worth ten crores in Goa. Racing against time and a corrupt police inspector, they embark on a chaotic journey filled with misadventures, misunderstandings, and comic situations. The film blends slapstick humor with fast-paced adventure.', 'Riteish Deshmukh, Arshad Warsi, Javed Jaffrey, Aashish Chaudhary, Sanjay Dutt', 'https://upload.wikimedia.org/wikipedia/en/thumb/6/60/Dhamaal_2007.jpg/250px-Dhamaal_2007.jpg', '2026-02-12 11:49:48.000', NULL),
(37, 'Uri: The Surgical Strike', 'Uri: The Surgical Strike is a 2019 Hindi military action film directed by Aditya Dhar. The film is based on the 2016 Uri attack and the subsequent surgical strike carried out by the Indian Army across the Line of Control. It follows Major Vihaan Singh Shergill as he leads a covert mission to avenge the attack. The film combines patriotic themes, tactical military operations, and intense combat sequences.', 'Vicky Kaushal, Paresh Rawal, Yami Gautam, Mohit Raina, Kirti Kulhari', 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/URI_-_New_poster.jpg/250px-URI_-_New_poster.jpg', '2026-02-12 11:52:41.000', NULL),
(38, 'Zindagi na milegi dobara', 'Zindagi Na Milegi Dobara is a 2011 Hindi coming-of-age road film directed by Zoya Akhtar. The story follows three childhood friends who reunite for a bachelor trip across Spain, where they confront personal fears, unresolved conflicts, and life-changing decisions. Through adventure sports, emotional conversations, and evolving relationships, the film explores themes of friendship, love, self-discovery, and living life to the fullest.', 'Hrithik Roshan, Farhan Akhtar, Abhay Deol, Katrina Kaif, Kalki Koechlin', 'https://upload.wikimedia.org/wikipedia/en/thumb/1/17/Zindagi_Na_Milegi_Dobara.jpg/250px-Zindagi_Na_Milegi_Dobara.jpg', '2026-02-12 11:54:10.000', NULL),
(39, 'Tumbaad', 'Tumbbad is a 2018 Hindi period horror fantasy film directed by Rahi Anil Barve. Set in pre-independence India, the story follows Vinayak Rao, who becomes obsessed with discovering a hidden ancestral treasure guarded by a cursed deity named Hastar. As greed consumes him over the years, the film explores themes of ambition, morality, and the destructive nature of unchecked desire, blending folklore with atmospheric horror.', 'Sohum Shah, Jyoti Malshe, Anita Date-Kelkar, Ronjini Chakraborty', 'https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Tumbbad_poster.jpg/250px-Tumbbad_poster.jpg', '2026-02-12 11:56:13.000', NULL),
(40, 'Swatantrya Veer Savarkar', 'Swatantrya Veer Savarkar is a 2024 biographical historical drama based on the life of Vinayak Damodar Savarkar, an Indian freedom fighter, political activist, and writer. The film traces his revolutionary activities against British rule, his imprisonment in the Cellular Jail in the Andaman and Nicobar Islands, and his ideological influence on India?s independence movement.', 'Randeep Hooda, Ankita Lokhande, Amit Sial, Rajesh Khera', 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b7/Swatantrya_Veer_Savarkar.jpg/250px-Swatantrya_Veer_Savarkar.jpg', '2026-02-12 11:58:19.000', NULL),
(41, 'Pawankhind', 'Pawankhind is a 2022 Marathi historical war film directed by Digpal Lanjekar. The film depicts the legendary Battle of Pavan Khind, where Baji Prabhu Deshpande and a small group of Maratha warriors made a heroic last stand against a massive enemy force to ensure the safe escape of Chhatrapati Shivaji Maharaj. The story highlights sacrifice, loyalty, and unwavering bravery.', 'Chinmay Mandlekar, Mrinal Kulkarni, Ajay Purkar, Prajakta Mali', 'https://upload.wikimedia.org/wikipedia/en/thumb/0/00/Pawankhind_film.jpg/250px-Pawankhind_film.jpg', '2026-02-12 22:38:20.000', NULL),
(42, 'Mumbai-Pune-Mumbai', 'Mumbai-Pune-Mumbai is a 2010 Marathi romantic drama directed by Satish Rajwade. The film follows a young woman from Mumbai who visits Pune to meet a prospective groom. When circumstances lead her to spend an entire day with a stranger from Pune, their contrasting personalities spark witty conversations, cultural clashes, and unexpected emotional bonding. The story unfolds over a single day, exploring love, identity, and connection.', 'Swapnil Joshi, Mukta Barve', 'https://upload.wikimedia.org/wikipedia/en/thumb/8/87/Mumbai-Pune-Mumbai.jpg/250px-Mumbai-Pune-Mumbai.jpg', '2026-02-12 22:40:55.000', NULL),
(43, 'Ashi hi Banwa Banwi', 'Ashi Hi Banwa Banwi is a 1988 Marathi comedy film directed by Sachin Pilgaonkar. The story revolves around two friends who disguise themselves as married couples to secure rental accommodation, leading to a chain of hilarious misunderstandings and chaotic situations. Known for its iconic dialogues and timeless humor, the film remains a cult classic in Marathi cinema.', 'Ashok Saraf, Sachin Pilgaonkar, Laxmikant Berde, Supriya Pilgaonkar, Priya Arun', 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f9/Ashi_Hi_Banwa_Banwi.jpg/250px-Ashi_Hi_Banwa_Banwi.jpg', '2026-02-12 22:42:14.000', NULL),
(44, 'Zapatlela', 'Zapatlela is a 1993 Marathi horror-comedy film directed by Mahesh Kothare. The story follows a ventriloquist doll named Tatya Vinchu that becomes possessed by the spirit of a notorious criminal. As the doll attempts to regain human form, a series of comic and suspenseful events unfold. The film is remembered for its unique concept, special effects, and blend of humor with horror.', 'Mahesh Kothare, Laxmikant Berde, Kishori Ambiye, Dilip Prabhavalkar', 'https://upload.wikimedia.org/wikipedia/en/thumb/7/71/Zapatlela_1.jpg/250px-Zapatlela_1.jpg', '2026-02-12 22:43:50.000', NULL),
(45, 'Dharmaveer', 'Dharmaveer is a 2022 Marathi biographical political drama directed by Pravin Tarde. The film is based on the life of Anand Dighe, a prominent Shiv Sena leader from Thane. It portrays his leadership style, strong connection with the people, and his influence in Maharashtra politics, highlighting themes of loyalty, ideology, and grassroots leadership.', 'Prasad Oak, Kshitij Date, Makarand Padhye, Snehal Tarde', 'https://upload.wikimedia.org/wikipedia/en/1/13/Dharmaveer_Marathi_film.jpeg', '2026-02-12 22:45:35.000', NULL),
(46, 'Juna Furniture', 'Juna Furniture is a 2024 Marathi drama film that explores the emotional value of old belongings and the memories attached to them. The story revolves around a middle-class family facing internal conflicts, generational differences, and financial struggles, where an old piece of furniture becomes symbolic of relationships, nostalgia, and identity.', 'Sachin Khedekar, Mahesh Manjrekar, Upendra Limaye, Sameer Dharmadhikari', 'https://upload.wikimedia.org/wikipedia/en/thumb/5/51/Juna_Furniture.jpg/250px-Juna_Furniture.jpg', '2026-02-12 22:47:05.000', NULL),
(47, 'Katyar Kaljat Ghusli', 'Katyar Kaljat Ghusli is a 2015 Marathi musical drama directed by Subodh Bhave. The film is based on the iconic Marathi stage play and revolves around a musical rivalry between two classical singers. Set in a princely state, the story explores themes of ego, devotion to art, mentorship, and the transformative power of Hindustani classical music.', 'Sachin Pilgaonkar, Subodh Bhave, Amruta Khanvilkar, Mrunmayee Deshpande', 'https://upload.wikimedia.org/wikipedia/en/thumb/3/35/Katyar_Kaljat_Ghusali_%28film%29.jpg/250px-Katyar_Kaljat_Ghusali_%28film%29.jpg', '2026-02-12 22:48:38.000', NULL),
(48, 'Vantilator', 'Ventilator is a 2016 Marathi family drama directed by Rajesh Mapuskar. The story revolves around a large family that gathers in a Mumbai hospital when their elderly relative is put on ventilator support. As relatives reconnect, unresolved conflicts, emotional bonds, and generational differences surface. The film balances humor and sentiment while portraying the importance of family relationships.', 'Ashutosh Gowariker, Jitendra Joshi, Sulabha Deshpande, Sukanya Kulkarni', 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0d/Ventilator_Poster.jpg/250px-Ventilator_Poster.jpg', '2026-02-12 22:51:22.000', NULL),
(49, 'Dr. Prakash Baba Aamte', 'Dr. Prakash Baba Amte - The Real Hero is a 2014 Marathi biographical drama based on the life of social activist Dr. Prakash Amte and his wife Dr. Mandakini Amte. The film portrays their dedicated service to tribal communities in the remote forests of Hemalkasa, highlighting themes of compassion, sacrifice, humanitarian work, and social reform.', 'Nana Patekar, Sonali Kulkarni, Mohan Agashe, Tejashri Pradhan', 'https://upload.wikimedia.org/wikipedia/en/thumb/9/91/Dr._Prakash_Baba_Amte_%E2%80%93_The_Real_Hero_%282014_film%29_poster.jpg/250px-Dr._Prakash_Baba_Amte_%E2%80%93_The_Real_Hero_%282014_film%29_poster.jpg', '2026-02-12 22:54:36.000', NULL),
(50, 'Gulabjaam', 'Gulabjaam is a 2018 Marathi comedy-drama directed by Sachin Kundalkar. The film follows Aditya, a young man who returns from London to Pune to reconnect with his roots and learn traditional Maharashtrian cooking from an experienced homemaker. Through food, conversations, and evolving friendships, the story explores identity, nostalgia, cultural pride, and personal growth.', 'Siddharth Chandekar, Sonali Kulkarni, Chinmay Udgirkar', 'https://upload.wikimedia.org/wikipedia/en/thumb/f/ff/Gulabjaam.jpg/250px-Gulabjaam.jpg', '2026-02-12 22:58:43.000', NULL),
(51, 'Happy New Year', 'Happy New Year is a 2014 Bollywood heist-comedy film directed by Farah Khan. The story follows Charlie, a street fighter who assembles a team of six misfits to participate in a prestigious international dance competition in Dubai. However, their real motive is to execute a carefully planned diamond heist and seek revenge against a powerful businessman who betrayed Charlie’s father. The film blends action, comedy, emotion, and high-energy dance performances, revolving around friendship, redemption, and patriotism.', NULL, 'https://i.pinimg.com/736x/37/41/33/374133718551dfcfa4c58819e61f4835.jpg', '2026-02-14 19:25:51.000', 'Shah Rukh Khan, Deepika Padukone, Abhishek Bachchan, Boman Irani, Sonu Sood, Vivaan Shah, Jackie Shroff');


/* Table: reviews */
DROP TABLE IF EXISTS `reviews`;
CREATE TABLE `reviews` (
  `id` int NOT NULL AUTO_INCREMENT,
  `movie_id` int NOT NULL,
  `user_name` varchar(100) NOT NULL,
  `rating` int NOT NULL,
  `review` text NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `movie_id` (`movie_id`),
  CONSTRAINT `reviews_ibfk_1` FOREIGN KEY (`movie_id`) REFERENCES `movies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `reviews_chk_1` CHECK ((`rating` between 1 and 5))
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
INSERT INTO `reviews` VALUES
(9, 47, 'Pushkraj', 5, 'Good\n', '2026-02-12 22:51:55.000'),
(10, 24, 'Dhammoday', 5, 'God level acting', '2026-02-12 22:52:28.000');


/* Table: users */
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `email` varchar(150) NOT NULL,
  `password` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `role` varchar(50) DEFAULT 'user',
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
INSERT INTO `users` VALUES
(1, 'Pushkraj kulkarni', 'pushkraj@gmai.com', '$2b$10$FnLIf3sTUUlo6mb/iPsjZeltMhGWmK9lbDpF.4UUV/Rv.8FYOCVUm', '2026-02-09 14:47:17.000', 'user'),
(2, 'Atharva kulkarni', 'atharva@gmail.com', '$2b$10$oCaW8scmU7u9W9koBNZkOO7p9n2Ba4rftDx6GCwtMy.eBmq4PxGwW', '2026-02-09 14:47:38.000', 'user'),
(3, 'Heramb Dharmadhikari', 'heramb69@gmail.com', '$2b$10$EEq6aSto4prkdVwo9/x4AeKuIYCYrJV/CjAmYnOLX.HPObIg60DU2', '2026-02-11 14:02:54.000', 'user'),
(4, 'Dhammoday Kale ', 'dhammoday@gmail.com', '$2b$10$K7Jw4x2rq./ZcarjWgOsjOoaZLNXEt19Gsqph5SXyEs2o.OSBTZhC', '2026-02-13 22:32:41.000', 'user'),
(5, 'Pushkraj Kulkarni', 'pushkrajkulkarni2007@gmail.com', '$2b$10$2b7fSPLrDdVNxhCWf0FUGe5d5iTpW2blFzCy08x8C8zAbaB92FGtu', '2026-02-14 19:22:43.000', 'admin'),
(6, 'sujit kulkarni', 'sujit123@gmail.com', '$2b$10$T45.nIg9o6PN7gYpdHDkKe4HDnNaWeLh.abSVdQaosteaoCIlUgcW', '2026-02-14 20:01:42.000', 'admin');

